# Generated by Django 4.2.10 on 2024-02-24 16:07

from django.db import migrations


def create_groups(apps, schema_migration):
    User = apps.get_model('users', 'User')
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    add_question = Permission.objects.get(codename='add_question')

    teachers_permissions = [
        add_question
    ]

    teachers = Group(name='teachers')
    teachers.save()

    teachers.permissions.set(teachers_permissions)

    for user in User.objects.all():
        if user.role == 'TEACHER':
            teachers.user_set.add(user)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_groups)
    ]
