# Generated by Django 4.2.10 on 2024-02-25 08:00

from django.db import migrations


def add_permissions(apps, schema_migration):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    view_question = Permission.objects.get(codename='view_question')
    change_question = Permission.objects.get(codename='change_question')
    delete_question = Permission.objects.get(codename='delete_question')

    teachers = Group.objects.get(name='teachers')

    teachers.permissions.add(view_question)
    teachers.permissions.add(change_question)
    teachers.permissions.add(delete_question)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20240224_1607"),
    ]

    operations = [
        migrations.RunPython(add_permissions)
    ]
