# Generated by Django 4.2.10 on 2024-03-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_first_name_alter_user_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                help_text="از نام واقعی خود استفاده کنید.", max_length=150
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                help_text="از نام خانوادگی واقعی خود استفاده کنید.", max_length=150
            ),
        ),
    ]
