# Generated by Django 4.2.10 on 2024-02-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("answer", models.FloatField()),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
