# Generated by Django 4.2.10 on 2024-02-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_answer"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Answer",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="answer",
            new_name="true_answer",
        ),
        migrations.AddField(
            model_name="question",
            name="user_answer",
            field=models.FloatField(default=0),
        ),
    ]
