# Generated by Django 4.2.10 on 2024-02-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_quiz_questionanswer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quiz",
            old_name="owner",
            new_name="designer",
        ),
        migrations.AddField(
            model_name="quiz",
            name="duration",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
