# Generated by Django 4.2.10 on 2024-02-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_delete_answer_rename_answer_question_true_answer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="user_answer",
            field=models.FloatField(),
        ),
    ]
