# Generated by Django 4.2.10 on 2024-03-06 06:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quiz", "0007_alter_questionanswer_user_answer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questionanswer",
            name="user",
        ),
        migrations.CreateModel(
            name="QuizAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "percent",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(100)]
                    ),
                ),
                ("answer_duration", models.PositiveIntegerField()),
                ("date_answered", models.DateTimeField(auto_now_add=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="quiz.quiz"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="questionanswer",
            name="quiz_answer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="quiz.quizanswer",
            ),
            preserve_default=False,
        ),
    ]
