# Generated by Django 4.2.10 on 2024-03-07 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0008_remove_questionanswer_user_quizanswer_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quiz",
            options={"verbose_name_plural": "quizzes"},
        ),
        migrations.AddField(
            model_name="quizanswer",
            name="date_started",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
