# Generated by Django 4.2.10 on 2024-03-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0009_alter_quiz_options_quizanswer_date_started"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="answer_published",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quiz",
            name="is_published",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
