# Generated by Django 4.2.10 on 2024-03-16 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0010_quiz_answer_published_quiz_is_published"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="date_added",
        ),
    ]
